spring.application.name=pachucrud

server.port=3035
server.http2.enabled=true
spring.grpc.server.port=9090
logging.level.org.springframework.grpc=DEBUG
logging.level.org.apache.coyote.http2=DEBUG
spring.mvc.async.request-timeout=300000

# DATABASE CONNECTION
spring.datasource.url=jdbc:postgresql://localhost:5432/my_database
spring.datasource.username=user
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver

# HIBERNATE SETTINGS
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true

# REDIS
spring.data.redis.host=localhost
spring.data.redis.port=6379

# REDIS LETTUCE POOL
spring.redis.lettuce.pool.max-active=16
spring.redis.lettuce.pool.max-idle=8
spring.redis.lettuce.pool.min-idle=2