spring.application.name=pachucrud
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

server.port=3035
server.http2.enabled=true
spring.grpc.server.port=9090
# Since you are using the Web starter, this is the port that matters:
logging.level.org.springframework.grpc=DEBUG
# This will show you the HTTP/2 frames coming into Tomcat
logging.level.org.apache.coyote.http2=DEBUG
spring.mvc.async.request-timeout=300000